---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
      name: '{{ container_name }}'
      image: traefik:v2.9
      pull: yes
      state: 'started'
      ports:
      - 80:80
      - 8080:8080
      volumes:
          - '{{ docker_dir }}/{{ container_name }}/:/etc/traefik'
          - '/var/run/docker.sock:/var/run/docker.sock'
      restart_policy: unless-stopped
